# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Downloads dSYM files from Apple to Firebase Crashlytics"
  lane :upload_dsym do
    download_dsyms(
        version: "latest",
        app_identifier: "com.o2oretail.dobrodelstore",
        username: "vlad.tokan96@mail.ru"
    )
    upload_symbols_to_crashlytics(gsp_path: "./DobrodelStore/GoogleService-Info.plist")
    clean_build_artifacts
  end
end
